### ISSUE TITLE
Correct way to embed JSON in a env var

### ISSUE THREAD

**Issue by tuxillo** [gookit/goutil#135]
Hi,

I'm having problems trying to embed a default JSON value for a env variable in my configuration file. Is this even allowed?

Config file:

```
test:
    credentials: >
        ${CREDENTIALS|{}}
    apiKey: ${API_KEY|AN_APIKEY}
    apiUri: ${API_URI|http://localhost:8888/v1/api}
```

Test program:

```
package main

import (
    "fmt"
	"google.golang.org/api/option"
	"github.com/gookit/config/v2"
	"github.com/gookit/config/v2/yamlv3"
)

type Setup struct {
	Credentials string `mapstructure:"credentials"`
	ApiKey      string `mapstructure:"apiKey"`
	ApiUri      string `mapstructure:"apiUri"`
}

type Configuration struct {
	Details Setup `mapstructure:"test"`
}

func main() {
	var st Configuration
	c := config.New("config")
	c.WithOptions(config.ParseEnv)
	c.AddDriver(yamlv3.Driver)

	err := c.LoadFiles("test.yml")
	if err != nil {
		panic(err)
	}

    c.Decode(&st)
	opt := option.WithCredentialsJSON([]byte(st.Details.Credentials))

    fmt.Printf("config creds: %s\n", opt)
}
```

It's adding an extra `}` at the end:

```
$ CREDENTIALS='{"type": "model"}' ./config
config creds: {"type": "model"}}
$ ./config
config creds: {}
```

Thanks.
